title: SoumyaK4 Hacked
description: Martial Arts for Body & Brain
baseurl: 
url: https://hacked.soumyak4.in

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
